# Generated by Django 6.0.5 on 2026-06-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetail',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
