# Generated by Django 6.0.5 on 2026-06-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_offerdetail_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='extra',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(default='basic', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='Basic Design', max_length=255),
            preserve_default=False,
        ),
    ]
